version: '3.7'

services:

  redmine:
    image: dina/redmine:v0.3
    container_name: redmine_server
    environment:
      - VIRTUAL_HOST=new-support.dina-web.net
      - REDMINE_DB_MYSQL=mariadb_redmine
      - REDMINE_DB_PASSWORD=secr3t
    volumes:
      - ./redmine-files:/usr/src/redmine/files
      - ./redmine-mail_config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./redmine-harvest/.env:/usr/src/redmine/mail-script/.env
      - ./redmine-harvest/receive_imap.sh:/usr/src/redmine/mail-script/receive_imap.sh
    links:
      - mariadb:mariadb_redmine

  mariadb:
    image: mariadb:10.1
    container_name: redmine_database
    environment:
      - MYSQL_DATABASE=redmine
      - MYSQL_ROOT_PASSWORD=secr3t
    volumes:
      - ./redminedb-init.d:/docker-entrypoint-initdb.d
      - ./mysql_datadir:/var/lib/mysql

networks:
  default:
    external:
       name: redmine 
